### ISSUE TITLE
Asking information about licence

### ISSUE THREAD

**Issue by annp1987** [commonism/python-libnetfilter#2]
Hi, 
I'm An, I'm a openstack neutron developer from Fujitsu. Thanks for your great works. Currently, I'm working on security group logging for openstack neutron [1]. I found your source code as useful for security group logging feature. However, I didn't saw any licences of this code. Is there allow us use your some source code for our feature? 

[1] https://review.openstack.org/#/c/445827/4

Thanks,
An

**Comment by commonism** [comment]
Yes.
